language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7
  
matrix:
  allow_failures:
    - php: 7  

before_script:
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpspec run
